# Used by matrix.sh to build the same connector at two different versions
# on top of the same base image. The only build-time variable is
# MODSEC_NGINX_VERSION.

FROM nginx:1.22.1-alpine AS builder

ARG MODSEC_VERSION=v3.0.8
ARG MODSEC_NGINX_VERSION

RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
        autoconf automake ca-certificates curl-dev g++ gcc \
        git libc-dev libstdc++ libtool make openssl-dev \
        pcre-dev pcre2-dev zlib-dev linux-headers \
        yajl-dev libxml2-dev

WORKDIR /sources

RUN git clone --branch ${MODSEC_VERSION} --depth 1 --recursive \
        https://github.com/SpiderLabs/ModSecurity.git && \
    cd ModSecurity && \
    ./build.sh && \
    ./configure --prefix=/usr/local/modsecurity && \
    make -j$(nproc) install

RUN git clone --branch ${MODSEC_NGINX_VERSION} --depth 1 \
        https://github.com/SpiderLabs/ModSecurity-nginx.git && \
    wget -q http://nginx.org/download/nginx-1.22.1.tar.gz && \
    tar -xzf nginx-1.22.1.tar.gz && \
    cd nginx-1.22.1 && \
    ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx && \
    make modules

FROM owasp/modsecurity:nginx-alpine

COPY --from=builder /sources/nginx-1.22.1/objs/ngx_http_modsecurity_module.so \
     /usr/lib/nginx/modules/ngx_http_modsecurity_module.so

